databases:
  - name: botanical_buddies
    databaseName: botanical_buddies
    user: botanical_buddies_user
    plan: free
services:
  - type: web
    name: botanical-buddies
    runtime: ruby
    plan: free
    buildCommand: "./render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: botanical_buddies
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
