databases:
  - name: BotanicalBuddies
    databaseName: BotanicalBuddies
    user: BotanicalBuddies
    plan: free

services:
  - type: web
    name: BotanicalBuddies
    runtime: ruby
    plan: free
    buildCommand: "./render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BotanicalBuddies
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
