development:
  cloud_name: <=% Rails.application.credentials.dig(:CLOUD_NAME) =%>
  api_key: <=% Rails.application.credentials.dig(:CLOUD_KEY) =%>
  api_secret: <=% Rails.application.credentials.dig(:CLOUD_SECRET) =%>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <=% Rails.application.credentials.dig(:CLOUD_NAME) =%>
  api_key: <=% Rails.application.credentials.dig(:CLOUD_KEY) =%>
  api_secret: <=% Rails.application.credentials.dig(:CLOUD_SECRET) =%>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <=% Rails.application.credentials.dig(:CLOUD_NAME) =%>
  api_key: <=% Rails.application.credentials.dig(:CLOUD_KEY) =%>
  api_secret: <=% Rails.application.credentials.dig(:CLOUD_SECRET) =%>
  enhance_image_tag: true
  static_file_support: false
